name: Frontend CI-CD Pipeline

# 자동화 발생 시점 설정
on:
  push:
    branches: [ "main" ]

# 트리거 발생 시 할 일
jobs:
  build-and-push:
    runs-on: ubuntu-latest # 깃허브가 제공하는 최신 리눅스 컴퓨터 빌려 쓰기
    
    steps:
    # 내 소스 코드 다운로드 받기
    - name: Checkout source code
      uses: actions/checkout@v4

    # 도커 허브 로그인하기 (비밀번호는 보안을 위해 시크릿 변수 처리)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: hshs99
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # buildx 세팅하기 (linux/amd64 크로스 빌드용)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 빌드하고 도커 허브에 밀어 올리기
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: hshs99/frontend:${{ github.sha }} # 또는 커밋 번호 버전

# ArgoCD 저장소를 가져와서 YAML 파일 내부의 이미지 태그를 방금 만든 고유 번호로 치환 후 push
    - name: Update Kubernetes Manifest in ArgoCD Repo
      run: |
        # 1. ArgoCD 배포 명세서 저장소를 가상 컴퓨터에 clone 받기
        git clone https://${{ secrets.GH_TOKEN }}@github.com/JeongHui-seong/GCP-K8s-ArgoCD.git argocd-repo
        cd argocd-repo
        
        # 2. 리눅스 sed 명령어로 kubernetes-manifest.yaml 안의 프론트엔드 이미지 태그를 최신 태그로 자동 수정
        sed -i 's|image: hshs99/frontend:.*|image: hshs99/frontend:${{ github.sha }}|g' kubernetes-manifest.yaml
        
        # 3. 변경 사항 자동 커밋 및 배포 레포로 Push
        git config --global user.email "jgmltjd99@naver.com"
        git config --global user.name "Github Actions - jhs"
        git add .
        git commit -m "Automated deployment: update frontend image to ${{ github.sha }} version"
        git push origin main

# ArgoCD가 동기화하고 파드를 롤링 업데이트할 때까지 '기다려준 후' 헬스체크 시작
    - name: Web Health Check
      run: |
        echo "ArgoCD가 클러스터에 새 파드를 반영할 때까지 40초간 대기"
        sleep 90 # Push 직후 바로 헬스체크를 하면 옛날 정상 파드에 테스트하게 되므로, 새 파드가 뜰 시간을 기다려줌

        echo "프론트엔드 상태 검사"
        for i in {1..10}; do
          STATUS_CODE=$(curl -k -o /dev/null -s -w "%{http_code}" "https://${{ secrets.LB_DOMAIN }}")
          
          if [ "$STATUS_CODE" = "200" ]; then
            echo "정상 작동"
            exit 0
          fi
          
          sleep 10
        done

        echo "에러가 났습니다."
        exit 1

    # 3단계: 자동 롤백 (Web Health Check 실패 시에만 발동!)
    - name: Automated Rollback on Failure
      if: failure() 
      run: |
        echo "배포 장애 감지! ArgoCD Manifest 레포지토리로 이동하여 롤백을 수행합니다."
        
        # 배포 명세서 폴더로 재진입
        cd argocd-repo
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 수정한 '이미지 태그 변경 커밋'을 그대로 취소(Revert)
        git revert --no-edit HEAD

        git push origin main